"""
Codegen: walks the AST and emits .mlvs assembly text.
"""

import re

from mlvm.const import ROM_START
from mlvm.bus import MLVMBus
from mlvm.devices import MLVMProcessor
from mlvm.instructions import instruction_from_name
from .ast_nodes import (
    Expr,
    StaticVarDecl,
    StaticBlockDecl,
    DataBlockDecl,
    FunctionDecl,
    BeginMarker,
    MacroExpansionComment,
    SymbolTarget,
    DerefTarget,
    FieldTarget,
    SetStmt,
    CallStmt,
    IncrDecrStmt,
    ReturnStmt,
    RtiStmt,
    FrameOpStmt,
    IfStmt,
    WhileStmt,
    AsmBlock,
    AsmToken,
    AsmAddressOf,
    AsmLabel,
    AsmDirective,
)
from .grammar import (
    VALUE_RE,
    SYMBOL_RE,
    EXPRESSION_OPERATOR_PRECEDENCE,
    EXPRESSION_OPERATOR_INSTRUCTION_MAP,
    UNARY_OPERATORS,
    TYPE_READ_SUFFIX,
    INVERSE_REGISTERS,
    var_read_suffix,
    var_write_suffix,
    pointee_type,
    is_pointer_type,
    is_block_type,
    block_element_type,
)

# Sentinel: result deferred into scratch register D instead of the real stack
_DREG_MARKER = object()

# Sentinel: result left sitting in C untouched, ready for the next operator to consume
_CREG_MARKER = object()


class Codegen:
    _PUSH16 = {"PSHA", "PSHB", "PSHC", "PSHD", "PSHI"}
    _PULL16 = {"PULA", "PULB", "PULC", "PULD"}
    _PUSH8 = {"PSHA8", "PSHB8", "PSHC8", "PSHD8", "PSHI8"}
    _PULL8 = {"PULA8", "PULB8", "PULC8", "PULD8"}

    def __init__(self, symbols):
        self.symbols = symbols
        self.asm = ""

        self.local_scope = None  # the current function's LocalScope, or None at top level
        self.pending_pushes = 0  # bytes of T-drift in flight

        self.cur_conditional_id = 0
        self.cur_loop_id = 0

        # Collected and flushed once at the end, behind a jump that skips the section
        self.pending_data_blocks = []

    def generate(self, program):
        self.asm = "/* Generated by MLVC Compiler */\n\n"
        self.asm += f".offset {hex(ROM_START)}\n"
        self.asm += "JMI $mlvc_program_start\n\n"
        for node in program:
            self.emit_top_level(node)

        if self.pending_data_blocks:
            self.asm += "\n/* ROM data blocks */\n"
            self.asm += "JMI $mlvc_data_section_end\n"
            for block in self.pending_data_blocks:
                self.emit_data_block(block)
            self.asm += "mlvc_data_section_end:\n"

        return self.asm

    # Values per .byte/.word line, cosmetic
    _DATA_CHUNK_SIZE = 16

    def emit_data_block(self, node):
        self.asm += f"\n/* data block {node.name} */\n"
        self.asm += f"{self.asm_prefix_var(node.name)}:\n"

        if node.source_string is not None:
            # One string literal
            self.asm += f".byte {node.source_string} 0\n"
            return

        directive = "byte" if self.symbols.type_size(node.elem_type) == 1 else "word"
        for i in range(0, len(node.values), self._DATA_CHUNK_SIZE):
            chunk = node.values[i : i + self._DATA_CHUNK_SIZE]
            self.asm += f".{directive} {' '.join(str(v) for v in chunk)}\n"

    def asm_prefix_var(self, name):
        return f"mlvc_static_var_{name}"

    def asm_prefix_function(self, name):
        return f"mlvc_function_{name}"

    def append_instruction(self, instruction):
        mnemonic = instruction.split(" ", 1)[0]

        if mnemonic in self._PUSH16:
            self.pending_pushes += 2
        elif mnemonic in self._PUSH8:
            self.pending_pushes += 1
        elif mnemonic in self._PULL16:
            self.pending_pushes -= 2
        elif mnemonic in self._PULL8:
            self.pending_pushes -= 1
        elif mnemonic == "PSHN":
            self.pending_pushes += int(instruction.split(" ", 1)[1])
        elif mnemonic == "PULN":
            self.pending_pushes -= int(instruction.split(" ", 1)[1])

        self.asm += f"    {instruction}\n"

    def _is_local(self, name):
        return self.local_scope is not None and name in self.local_scope

    def _local_imm(self, name):
        # pending_pushes corrects T for whatever's in flight mid-statement
        rel_offset, _ = self.local_scope.var_offsets[name]
        return rel_offset - self.local_scope.frame_bytes - self.pending_pushes

    def emit_local_address(self, name):
        self.append_instruction(f"SOF {self._local_imm(name)}")

    def emit_literal_load(self, reg, value_str):
        # Narrow to a 1-byte immediate whenever the value's magnitude allows it
        value = int(value_str, 0)
        if 0 <= value <= 255:
            self.append_instruction(f"LI{reg}8 {value_str}")
        elif -128 <= value < 0:
            self.append_instruction(f"LI{reg}8S {value_str}")
        else:
            self.append_instruction(f"LI{reg} {value_str}")

    def emit_local_read(self, name, reg, suffix):
        self.append_instruction(f"RS{reg}{suffix} {self._local_imm(name)}")

    def emit_local_write(self, name, reg, suffix):
        self.append_instruction(f"WS{reg}{suffix} {self._local_imm(name)}")

    def emit_local_epilogue(self):
        if self.local_scope.frame_bytes:
            self.append_instruction(f"PULN {self.local_scope.frame_bytes}")

    def emit_top_level(self, node):
        if isinstance(node, FunctionDecl):
            self.emit_function(node)
        else:
            self.emit_statement(node)

    def emit_function(self, node):
        if node.address is not None:
            self.asm += f".seekpush {hex(node.address)}\n"

        self.asm += f"\n/* function definition: {node.name} */\n"
        self.asm += f"{self.asm_prefix_function(node.name)}:\n"

        prev_scope, prev_pending = self.local_scope, self.pending_pushes
        self.local_scope = node.local_scope
        self.pending_pushes = 0

        # One bulk T-adjustment, no memory touched
        # the frame is never read before being set
        if node.local_scope.frame_bytes:
            self.append_instruction(f"PSHN {node.local_scope.frame_bytes}")
        self.pending_pushes = 0  # the prologue's own push is accounted for via frame_bytes instead

        self.emit_statements(node.body)

        # Skip the epilogue+RET if already unconditional return/rti
        ends_in_return = len(node.body) > 0 and isinstance(node.body[-1], (ReturnStmt, RtiStmt))
        if not ends_in_return:
            self.emit_local_epilogue()
            self.append_instruction("RET")

        self.local_scope, self.pending_pushes = prev_scope, prev_pending

        if node.address is not None:
            self.asm += ".seekpop\n"
        self.asm += "\n"

    def emit_statements(self, statements):
        for stmt in statements:
            self.emit_statement(stmt)

    def emit_statement(self, stmt):
        if isinstance(stmt, (StaticVarDecl, StaticBlockDecl)):
            # var/alloc outside a function is always static, even nested in begin/if/while
            self.asm += f".set {self.asm_prefix_var(stmt.name)} {hex(stmt.address)}\n"
        elif isinstance(stmt, DataBlockDecl):
            self.pending_data_blocks.append(stmt)
        elif isinstance(stmt, BeginMarker):
            self.asm += "\nmlvc_program_start:\n"
        elif isinstance(stmt, MacroExpansionComment):
            self.asm += f"/* expanding macro {stmt.name} */\n"
        elif isinstance(stmt, SetStmt):
            self.emit_set(stmt)
        elif isinstance(stmt, CallStmt):
            self.emit_call(stmt.fn_name, stmt.args)
        elif isinstance(stmt, IncrDecrStmt):
            self.emit_incr_decr(stmt)
        elif isinstance(stmt, ReturnStmt):
            self.emit_return(stmt)
        elif isinstance(stmt, RtiStmt):
            self.emit_rti(stmt)
        elif isinstance(stmt, FrameOpStmt):
            self.emit_frame_op(stmt)
        elif isinstance(stmt, IfStmt):
            self.emit_if(stmt)
        elif isinstance(stmt, WhileStmt):
            self.emit_while(stmt)
        elif isinstance(stmt, AsmBlock):
            self.emit_asm_block(stmt)
        else:
            raise AssertionError(f"Unexpected statement: {stmt!r}")

    def emit_set(self, stmt):
        target = stmt.target

        # Literal into a static var, no register touched at all
        if (
            isinstance(target, SymbolTarget)
            and not self._is_local(target.name)
            and len(stmt.value.rpn) == 1
            and re.match(VALUE_RE, str(stmt.value.rpn[0]))
        ):
            suffix = var_write_suffix(self.symbols.resolve_type(target.name, self.local_scope))
            self.append_instruction(f"WII{suffix} ${self.asm_prefix_var(target.name)} {stmt.value.rpn[0]}")
            return

        output_register = self.solve_expression(stmt.value)

        if isinstance(target, SymbolTarget):
            var_type = self.symbols.resolve_type(target.name, self.local_scope)
            suffix = var_write_suffix(var_type)
            if self._is_local(target.name):
                self.emit_local_write(target.name, output_register, suffix)
            else:
                self.append_instruction(f"WI{output_register}{suffix} ${self.asm_prefix_var(target.name)}")

        elif isinstance(target, DerefTarget):
            if target.dest is None:
                # Computed address, explicit_type mandatory
                # value is always in A here, since solve_expression never returns "B".
                if output_register == "C":
                    self.append_instruction("SAC")
                    output_register = "A"
                self.solve_expression_address(target.expr, "A")
                self.append_instruction(f"WR{output_register}{var_write_suffix(target.explicit_type)}")

            elif re.match(VALUE_RE, target.dest):  # a literal/defined address, one hop
                suffix = var_write_suffix(target.explicit_type) if target.explicit_type else "8"
                self.append_instruction(f"WI{output_register}{suffix} {target.dest}")
            else:
                var_type = self.symbols.resolve_type(target.dest, self.local_scope)
                is_local = self._is_local(target.dest)

                if is_block_type(var_type):
                    # a block, one hop: the symbol is the first element's address
                    elem_type = target.explicit_type or block_element_type(var_type)
                    suffix = var_write_suffix(elem_type)
                    if is_local:
                        self.emit_local_write(target.dest, output_register, suffix)
                    else:
                        self.append_instruction(f"WI{output_register}{suffix} ${self.asm_prefix_var(target.dest)}")
                else:
                    # pointer var, two hops: read its stored value (the pointee address), then write through it
                    # moving the value out of C first if that's where it is
                    if output_register == "C":
                        self.append_instruction("SAC")
                        output_register = "A"
                    pointee = target.explicit_type or pointee_type(var_type)
                    suffix = var_write_suffix(pointee)
                    if is_local:
                        self.emit_local_read(target.dest, "C", "")  # fused: pointer's own stored value
                    else:
                        self.append_instruction(f"RIC ${self.asm_prefix_var(target.dest)}")
                    self.append_instruction(f"WR{output_register}{suffix}")

        elif isinstance(target, FieldTarget):
            folded = self.try_fold_chain_address(target.base, target.is_pointer_base, target.steps)

            if folded:
                # A folded address is a literal operand, so the value can stay in C, no conflict
                prefix, addr = folded
                self.append_instruction(f"W{prefix}{output_register}{var_write_suffix(target.final_type)} {addr}")
            else:
                # The computed field address lands in C, so move the value out first if needed
                if output_register == "C":
                    self.append_instruction("SAC")
                    output_register = "A"

                addr_expr = self._chain_addr_expr(target.base, target.is_pointer_base, target.steps)
                self.solve_expression_address(addr_expr, "A")
                self.append_instruction(f"WR{output_register}{var_write_suffix(target.final_type)}")

        else:
            raise AssertionError(f"Unexpected set target: {target!r}")

    def emit_call(self, fn_name, arg_exprs):
        # Args push straight from wherever solve_expression left them
        params = self.symbols.functions[fn_name].params
        for arg_expr, (_, ptype) in zip(arg_exprs, params):
            suffix = "8" if self.symbols.type_size(ptype) == 1 else ""
            if len(arg_expr.rpn) == 1 and re.match(VALUE_RE, str(arg_expr.rpn[0])):
                # a bare literal argument, push straight from ROM
                self.append_instruction(f"PSHI{suffix} {arg_expr.rpn[0]}")
            else:
                arg_reg = self.solve_expression(arg_expr)
                self.append_instruction(f"PSH{arg_reg}{suffix}")

        self.append_instruction(f"SRI ${self.asm_prefix_function(fn_name)} /* function call: {fn_name} */")

        # Clean up after call
        arg_bytes = sum(self.symbols.type_size(ptype) for _, ptype in params)
        if arg_bytes:
            self.append_instruction(f"PULN {arg_bytes}")

    def emit_incr_decr(self, stmt):
        var_type = self.symbols.resolve_type(stmt.target, self.local_scope)
        suffix = "8" if self.symbols.type_size(var_type) == 1 else ""
        mnemonic = "IN" if stmt.op == "incr" else "DE"

        if self._is_local(stmt.target):
            self.append_instruction(f"{mnemonic}S{suffix} {self._local_imm(stmt.target)}")
        else:
            self.append_instruction(f"{mnemonic}I{suffix} ${self.asm_prefix_var(stmt.target)}")

    def emit_expr_into_c(self, expr):
        """Evaluates expr into C. For literal/plain symbols. Shared by return and svi/ldi."""
        rpn = expr.rpn
        if len(rpn) == 1 and re.match(VALUE_RE, str(rpn[0])):
            self.emit_literal_load("C", str(rpn[0]))
        elif len(rpn) == 1 and re.match(SYMBOL_RE, str(rpn[0])):
            name = str(rpn[0])
            var_type = self.symbols.resolve_type(name, self.local_scope)
            if self._is_local(name):
                self.emit_local_read(name, "C", var_read_suffix(var_type))
            else:
                self.append_instruction(f"RIC{var_read_suffix(var_type)} ${self.asm_prefix_var(name)}")
        else:
            output_register = self.solve_expression(expr)
            if output_register != "C":
                self.append_instruction(f"SC{output_register}")

    def emit_return(self, stmt):
        # Bare return, leaves C alone
        if stmt.value is not None:
            self.emit_expr_into_c(stmt.value)

        if self.local_scope is not None:
            self.emit_local_epilogue()
            self.pending_pushes = 0

        self.append_instruction("RET")

    def emit_rti(self, stmt):
        if self.local_scope is not None:
            self.emit_local_epilogue()
            self.pending_pushes = 0
        self.append_instruction("RTI")

    def emit_frame_op(self, stmt):
        # svi <expr>; / ldi <expr>;
        # land the address in C then emit the bare opcode.
        self.emit_expr_into_c(stmt.value)
        self.append_instruction(stmt.op)

    def try_fold_constant(self, expr):
        """Returns expr's value if fully compile-time-constant, or None if not foldable."""
        stack = []
        for element in expr.rpn:
            if element in EXPRESSION_OPERATOR_PRECEDENCE:
                if len(stack) < 2:
                    return None
                b = stack.pop()
                a = stack.pop()
                if not (isinstance(a, str) and isinstance(b, str) and re.match(VALUE_RE, a) and re.match(VALUE_RE, b)):
                    return None
                c = self.evaluate_const_operation(
                    int(a, 0), int(b, 0), instruction_from_name(EXPRESSION_OPERATOR_INSTRUCTION_MAP[element])
                )
                stack.append(str(c))
            else:
                stack.append(element)

        if len(stack) == 1 and isinstance(stack[0], str) and re.match(VALUE_RE, stack[0]):
            return int(stack[0], 0)
        return None

    def emit_if(self, stmt):
        conditional_id = self.cur_conditional_id
        self.cur_conditional_id += 1

        const_value = self.try_fold_constant(stmt.condition)
        if const_value is not None:
            # Constant condition, no need to evaluate at runtime, but still emit the bytes of the dead branch
            self.asm += "    /* if expression (compile-time constant) */\n"
            if const_value == 0:
                self.append_instruction(f"JMI $conditional_{conditional_id}_else /* if conditional (always false) */")
        else:
            self.asm += "    /* if expression */\n"
            output_register = self.solve_expression(stmt.condition)
            jump = f"J{INVERSE_REGISTERS[output_register]}I $conditional_{conditional_id}_else"
            self.asm += f"    {jump} /* if content block */\n"

        self.emit_statements(stmt.body)

        if stmt.else_body is not None:
            self.append_instruction(f"JMI $conditional_{conditional_id}_end /* skip else block */")
            self.asm += f"conditional_{conditional_id}_else: /* else content block */\n"
            self.emit_statements(stmt.else_body)
            self.asm += f"conditional_{conditional_id}_end: /* end if/else block */\n"
        else:
            self.asm += f"conditional_{conditional_id}_else: /* end if content block */\n"

    def emit_while(self, stmt):
        loop_id = self.cur_loop_id
        self.cur_loop_id += 1
        const_value = self.try_fold_constant(stmt.condition)

        if const_value == 0:  # never true, skip straight past the body
            self.asm += "    /* while condition (always false) */\n"
            self.append_instruction(f"JMI $loop_{loop_id}_end /* while entry (always false) */")
            self.asm += f"loop_{loop_id}_begin: /* while content block */\n"
            self.emit_statements(stmt.body)
            self.asm += f"loop_{loop_id}_end: /* end while block */\n"
            return

        if const_value is not None:  # always true, loop forever, without evaluating condition
            self.asm += "    /* while condition (always true) */\n"
            self.asm += f"loop_{loop_id}_begin: /* while content block */\n"
            self.emit_statements(stmt.body)
            self.append_instruction(f"JMI $loop_{loop_id}_begin /* while condition (always true) */")
            self.asm += f"loop_{loop_id}_end: /* end while block */\n"
            return

        # condition checked once at the bottom, not duplicated top and bottom
        # the first iteration of the loop just jumps to the condition at the bottom first
        self.append_instruction(f"JMI $loop_{loop_id}_cond /* while entry */")
        self.asm += f"loop_{loop_id}_begin: /* while content block */\n"

        self.emit_statements(stmt.body)

        self.asm += f"loop_{loop_id}_cond: /* while condition */\n"
        output_register = self.solve_expression(stmt.condition)
        self.append_instruction(f"J{output_register}I $loop_{loop_id}_begin /* while conditional jump */")
        self.asm += f"loop_{loop_id}_end: /* end while block */\n"

    def emit_asm_block(self, node):
        self.asm += "    /* asm block */\n"
        for line in node.lines:
            if isinstance(line, AsmLabel):
                self.asm += f"{line.text}\n"
            elif isinstance(line, AsmDirective):
                self.asm += f"{line.text}\n"
            elif isinstance(line, AsmAddressOf):
                if line.name in self.symbols.static_vars:
                    self.append_instruction(f"${self.asm_prefix_var(line.name)}")
                else:
                    self.append_instruction(f"${self.asm_prefix_function(line.name)}")
            elif isinstance(line, AsmToken):
                self.append_instruction(line.text)
            else:
                raise AssertionError(f"Unexpected asm block line: {line!r}")
        self.asm += "    /* end asm block */\n"

    def _chain_addr_expr(self, base_name, is_pointer_base, steps):
        """Builds an address Expr for base_name plus a chain of ('field',name)/('index',expr)
        steps, walking the symbol table one step at a time so any depth of nesting works."""
        if is_pointer_base:
            cur_type = pointee_type(self.symbols.resolve_type(base_name, self.local_scope))
            rpn = [base_name]  # bare name reads the pointer's own stored value
        else:
            cur_type = self.symbols.resolve_type(base_name, self.local_scope)
            rpn = [f"@{base_name}"]

        for kind, value in steps:
            if kind == "field":
                offset, cur_type = self.symbols.structs[cur_type].fields[value]
                rpn += [str(offset), "+"]
            else:  # "index"
                elem_type = block_element_type(cur_type)
                rpn += value.rpn + [str(self.symbols.type_size(elem_type)), "*", "+"]
                cur_type = elem_type

        return Expr(rpn=rpn)

    def try_fold_chain_address(self, base_name, is_pointer_base, steps):
        """base.field...<literal>... addresses are compile-time constants whenever every index
        in the chain is a literal, so this folds the whole thing into one fused operand instead
        of computing it at runtime. Returns (prefix, addr) or None if not foldable."""
        if is_pointer_base:
            return None

        cur_type = self.symbols.resolve_type(base_name, self.local_scope)
        total_offset = 0
        for kind, value in steps:
            if kind == "field":
                offset, cur_type = self.symbols.structs[cur_type].fields[value]
                total_offset += offset
            else:  # "index"
                if not (len(value.rpn) == 1 and re.match(VALUE_RE, str(value.rpn[0]))):
                    return None
                elem_type = block_element_type(cur_type)
                total_offset += int(str(value.rpn[0]), 0) * self.symbols.type_size(elem_type)
                cur_type = elem_type

        if self._is_local(base_name):
            return "S", str(self._local_imm(base_name) + total_offset)

        static_addr = self.symbols.resolve_static_address(base_name)
        if static_addr is None:
            return None
        return "I", str(static_addr + total_offset)

    def evaluate_const_operation(self, a, b, instruction):
        # Constant folding in the coolest way: run a virtual processor at compile time
        temp_cpu = MLVMProcessor(MLVMBus())
        temp_cpu.cur_instruction = instruction
        temp_cpu.cur_step = 0
        temp_cpu.reg_a = a
        temp_cpu.reg_b = b

        for _ in range(len(instruction)):
            temp_cpu.clock_neg()
            temp_cpu.clock_pos()

        return temp_cpu.reg_c

    def solve_expression_address(self, expr, preserve_register=None, preserve_dreg=False):
        """Evaluates expr as an address into C.
        preserve_register keeps a live sibling operand (A/B) safe across this nested solve
        preserve_dreg keeps a live deferred operand in D safe across this nested solve"""
        if preserve_register:
            self.append_instruction(f"PSH{preserve_register}")
        if preserve_dreg:
            self.append_instruction("PSHD")

        address_register = self.solve_expression(expr)

        if preserve_register:
            scratch = "B" if preserve_register == "A" else "A"
            if address_register != scratch:
                self.append_instruction(f"S{scratch}{address_register}")
            address_register = scratch

        if preserve_dreg:
            self.append_instruction("PULD")
        if preserve_register:
            self.append_instruction(f"PUL{preserve_register}")

        if address_register != "C":
            self.append_instruction(f"SC{address_register}")

    def solve_expression(self, expr):
        """Evaluates expr.rpn, returns the register holding the result ("A" or "C", never B)."""

        rpn = expr.rpn
        output_register = None
        stack = []

        # True while D holds an unconsumed deferred result, a second deferral falls back to the stack
        dreg_occupied = False

        def get_element(e, reg):
            nonlocal dreg_occupied

            if e is None:  # on the system stack, pull it from there directly
                self.append_instruction(f"PUL{reg}")

            elif e is _DREG_MARKER:  # result stored D rather than the real stack
                self.append_instruction(f"S{reg}D")
                dreg_occupied = False

            elif e is _CREG_MARKER:  # result already sitting in C, never staged anywhere
                if reg != "C":
                    self.append_instruction(f"S{reg}C")

            elif isinstance(e, tuple) and e[0] == "path":  # base.field...<index>..., any depth
                _, base_name, is_pointer_base, steps, final_type = e
                folded = self.try_fold_chain_address(base_name, is_pointer_base, steps)
                if folded:
                    prefix, addr = folded
                    self.append_instruction(f"R{prefix}{reg}{var_read_suffix(final_type)} {addr}")
                else:
                    addr_expr = self._chain_addr_expr(base_name, is_pointer_base, steps)
                    self.solve_expression_address(addr_expr, "B" if reg == "A" else None, preserve_dreg=dreg_occupied)
                    self.append_instruction(f"RD{reg}{var_read_suffix(final_type)}")

            elif isinstance(e, tuple) and e[0] == "call":  # ?fn_name(args), a call as an operand
                _, fn_name, args_exprs = e
                preserve_b = reg == "A"
                preserve_d = dreg_occupied

                if preserve_b:
                    self.append_instruction("PSHB")
                if preserve_d:
                    self.append_instruction("PSHD")

                self.emit_call(fn_name, args_exprs)  # leaves the return value in C, untouched below

                if preserve_d:  # D was pushed last, comes off first
                    self.append_instruction("PULD")
                if preserve_b:
                    self.append_instruction("PULB")

                if reg != "C":
                    self.append_instruction(f"S{reg}C")

            elif isinstance(e, tuple) and e[0] == "deref":  # [...] / [TYPE ...] dereference
                _, inner_tokens, inner_expr, explicit_type = e
                name = str(inner_tokens[0]) if len(inner_tokens) == 1 else None

                if name is not None and re.match(VALUE_RE, name):  # a literal/defined address, one hop
                    suffix = TYPE_READ_SUFFIX[explicit_type] if explicit_type else "8"
                    self.append_instruction(f"RI{reg}{suffix} {name}")

                elif name is not None and self._is_local(name) and is_block_type(self.local_scope.var_offsets[name][1]):
                    # a local block, one hop
                    elem_type = explicit_type or block_element_type(self.local_scope.var_offsets[name][1])
                    suffix = var_read_suffix(elem_type)
                    self.emit_local_read(name, reg, suffix)

                elif (
                    name is not None
                    and name in self.symbols.static_vars
                    and is_block_type(self.symbols.static_vars[name][0])
                ):
                    # an alloc'd block, one hop
                    elem_type = explicit_type or block_element_type(self.symbols.static_vars[name][0])
                    suffix = var_read_suffix(elem_type)
                    self.append_instruction(f"RI{reg}{suffix} ${self.asm_prefix_var(name)}")

                elif (
                    name is not None and self._is_local(name) and is_pointer_type(self.local_scope.var_offsets[name][1])
                ):
                    # local pointer, two hops
                    pointee = explicit_type or pointee_type(self.local_scope.var_offsets[name][1])
                    suffix = TYPE_READ_SUFFIX[pointee]
                    self.emit_local_read(name, "C", "")
                    self.append_instruction(f"RD{reg}{suffix}")

                elif (
                    name is not None
                    and name in self.symbols.static_vars
                    and is_pointer_type(self.symbols.static_vars[name][0])
                ):
                    # pointer var, two hops
                    pointee = explicit_type or pointee_type(self.symbols.static_vars[name][0])
                    suffix = TYPE_READ_SUFFIX[pointee]
                    self.append_instruction(f"RIC ${self.asm_prefix_var(name)}")
                    self.append_instruction(f"RD{reg}{suffix}")

                else:  # a computed address expression, one hop, defaults to u8 unless overridden
                    suffix = TYPE_READ_SUFFIX[explicit_type] if explicit_type else "8"
                    self.solve_expression_address(inner_expr, "B" if reg == "A" else None, preserve_dreg=dreg_occupied)
                    self.append_instruction(f"RD{reg}{suffix}")

            elif isinstance(e, str) and e.startswith("@"):  # address-of a var or function
                name = e[1:]
                if self._is_local(name):
                    self.emit_local_address(name)
                    if reg != "C":
                        self.append_instruction(f"S{reg}C")
                elif name in self.symbols.static_vars:
                    self.append_instruction(f"LI{reg} ${self.asm_prefix_var(name)}")
                elif name in self.symbols.functions:
                    self.append_instruction(f"LI{reg} ${self.asm_prefix_function(name)}")
                else:
                    raise AssertionError(f"Undefined symbol survived parsing: {name}")

            elif isinstance(e, str) and re.match(VALUE_RE, e):  # a literal
                self.emit_literal_load(reg, e)

            elif isinstance(e, str) and re.match(SYMBOL_RE, e):  # a plain variable reference
                var_type = self.symbols.resolve_type(e, self.local_scope)
                if self._is_local(e):
                    self.emit_local_read(e, reg, var_read_suffix(var_type))
                else:
                    self.append_instruction(f"RI{reg}{var_read_suffix(var_type)} ${self.asm_prefix_var(e)}")

            else:
                raise AssertionError(f"Bad expression element: {e!r}")

        def stage_result(i):
            # Shared tail once a result is in C: stays there if immediately consumed, else
            # defers to D or the real stack
            nonlocal output_register, dreg_occupied
            if i == (len(rpn) - 1):  # end of expression, answer is in C
                output_register = "C"
            elif rpn[i + 1] in EXPRESSION_OPERATOR_PRECEDENCE:
                stack.append(_CREG_MARKER)
            elif not dreg_occupied:
                self.append_instruction("SDC")
                stack.append(_DREG_MARKER)
                dreg_occupied = True
            else:
                self.append_instruction("PSHC")
                stack.append(None)

        for i, element in enumerate(rpn):
            if element in UNARY_OPERATORS:
                # Unary operators only ever read A, so unlike every other precedence entry these consume one RPN operand
                a = stack.pop()
                instruction = EXPRESSION_OPERATOR_INSTRUCTION_MAP[element]

                if isinstance(a, str) and re.match(VALUE_RE, a):
                    # both operands are const, fold this operation
                    # unary ops never read B, 0 is just a filler
                    c = self.evaluate_const_operation(int(a, 0), 0, instruction_from_name(instruction))
                    stack.append(str(c))
                else:
                    get_element(a, "A")
                    self.append_instruction(instruction)
                    stage_result(i)

            elif element in EXPRESSION_OPERATOR_PRECEDENCE:
                b = stack.pop()
                a = stack.pop()

                if isinstance(a, str) and isinstance(b, str) and re.match(VALUE_RE, a) and re.match(VALUE_RE, b):
                    # both operands are constants, fold this operation at compile time
                    c = self.evaluate_const_operation(
                        int(a, 0),
                        int(b, 0),
                        instruction_from_name(EXPRESSION_OPERATOR_INSTRUCTION_MAP[element]),
                    )
                    stack.append(str(c))
                else:
                    get_element(b, "B")
                    get_element(a, "A")
                    self.append_instruction(EXPRESSION_OPERATOR_INSTRUCTION_MAP[element])
                    stage_result(i)
            else:
                stack.append(element)

        if len(stack):  # one element left, load it into A as the result
            get_element(stack.pop(), "A")
            output_register = "A"

        return output_register
